name: Feature
description: Deliverable feature within an epic
title: "[Feature] "
labels:
  - "Type: Feature"
  - "Status: To do"
body:
  - type: input
    id: epic_link
    attributes:
      label: Epica relacionada
      description: Víncula la épica 8(si existe).
      placeholder: "#100"
    validations:
      required: false

  - type: input
    id: feature_summary
    attributes:
      label: Descripción
      description: Breve descripción de la funcionalidad.
      placeholder: "Carga masiva de los productos..."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Detalles
      description: ¿Qué hace esta funcionalidad? ¿Hay restricciones?
      placeholder: |
        Esta funcionalidad permitirá...
    validations:
      required: true

  - type: textarea
    id: stories
    attributes:
      label: Historias (asociadas)
      description: Vinclula las historias a manera de checklist.
      placeholder: |
        - [ ] #201 Como cliente, puedo consultar el catalogo...
        - [ ] #202 Como administrador, puedo eliminar el producto...
    validations:
      required: false
