name: User story
description: Historia de usuario con criterios de aceptación (WHO & WHY)
title: "[Story] "
labels:
  - "Type: Story"
  - "Status: To do"
body:
  - type: textarea
    id: story
    attributes:
      label: Historia de usuario
      description: Usa este formato “Como [persona], quiero que [acción] para [objetivo, fin último].”
      placeholder: |
        Como cliente, quiero seleccionar el producto y conocer sus características para decidir si lo agrego o no...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Criterios de aceptacipon
      description: Enlista elementos validables.
      placeholder: |
        - [ ] DADO X, CUANDO Y, ENTONCES Z
        - [ ] DADO un producto en el catálogo, CUANDO el cliente lo seleccione, ENTONCES despliega la descripción y una foto...
    validations:
      required: true

  - type: textarea
    id: subtasks
    attributes:
      label: Sub-tareas (opcional)
      description: Usa un checklist para temas técnicos.
      placeholder: |
        - [ ] Base de datos
        - [ ] Interface de usuario
        - [ ] Llamada a API
    validations:
      required: false
